import type { Config } from 'tailwindcss'

const config: Config = {
  // default colors

  content: ['./src/pages/**/*.{js,ts,jsx,tsx,mdx}', './src/components/**/*.{js,ts,jsx,tsx,mdx}', './src/app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      backgroundImage: {
        'student-dashboard-progress-bg': "url('/assets/images/student/dashboard/progress-bg.svg')",
        'header-bg': "url('/assets/images/landing-page/header-bg.svg')",
        'header-border-green': "url('/assets/images/landing-page/border-green.svg')",
        'header-border-red': "url('/assets/images/landing-page/border-red.svg')",
        'info-card-shape1': "url('/assets/card/info-card-shape1.svg')",
        'info-card-shape2': "url('/assets/card/info-card-shape2.svg')",
        'info-card-shape3': "url('/assets/card/info-card-shape3.svg')",
        'video-thumbnail': "url('/assets/images/landing-page/video-thumbnail.svg')",
        'about-us-banner': "url('/assets/images/about-us/banner.svg')",
        'about-us1': "url('/assets/images/about-us/about.png')",
        'our-story': "url('/assets/images/about-us/story-bg.svg')",
        'story-thumbnail': "url('/assets/images/about-us/story-thumbnail.png')",
        revolution1: "url('/assets/images/about-us/rev1.png')",
        revolution2: "url('/assets/images/about-us/rev2.png')",
        'loading-screen': "url('/assets/images/loading-screen/loading-screen.svg')",
        'learning-hub-lesson': "url('/assets/images/learning-hub/lesson-img.svg')",
        'games-tiles': "url('/assets/images/games/game-name.svg')",
        crossword: "url('/assets/images/games/cross-word.png')",
        wordsearch: "url('/assets/images/games/word-search.png')",
      },
      boxShadow: {
        'grade-box': '5px 0px 18px 0px rgba(185, 212, 208, 0.40)',
        'image-card': '0px 0px 10px 0px rgba(0, 0, 0, 0.08)',
        'row-shadow': '0px 0px 10px 0px rgba(0, 0, 0, 0.08)',
        'info-card-shadow': '0px 8px 16px 0px rgba(0, 0, 0, 0.10)',
        'play-button': '0px 4px 4px 0px rgba(0, 0, 0, 0.25)',
        tiles: '0px 0px 16px 0px #00000014',
        'input-shadow': '0px 1px 2px 0px #1018280D',
        'smart-card': '0px 0px 16px 0px #10182814',
        'lesson-card': '0px 8px 8px -4px #10182808,0px 20px 24px -4px #10182814',
        'subject-card': '0px 2px 5px -1px #E0E5EB',
        'student-rank': '0px 0px 60px 0px #00000014',
      },
      fontSize: {
        '2.5xl': '32px',
      },
      colors: {
        primary: '#4D9EF9',
        purple: '#753CBD',
        sliver: '#CBCDCD',
        green: '#0F947F',
        grey: '#4F4F4F',
        'lite-gray': '#505857',
        'lime-green': '#22CC9B',
        'dark-lime-green': '#36A593',
        'lite-black': '#3D3842',
        'dark-purple': '#260673',
        'nile-blue': '#0F3F62',
        'regent-gray': '#8695A0',
        'soft-blue': '#6183E4',
        'titan-white': '#E9EEFB',
        'dusty-gray': '#D5CECE',
        indigo: '#753CBD',
        'off-green': '#E9FAF5',
        'off-blue': '#EDF5FF',
        'soft-peach': '#F1ECF8',
        'hot-pink': '#E963C2',
        'vista-white': '#F8FAFC',
        mist: '#928F95',
        'lite-red': '#EB4E59',
        casal: '#30526A',
        slate: '#535A73',
        magnolia: '#F8F4FD',
        mango: '#FBCC58',
        pale: '#FEEFCB',
        'vamp-grey': '#4E4E50',
        'white-smoke': '#F5F4F4',
        zircon: '#F9F6FD',
        'ice-cold': '#BAEFE0',
        'dark-sky-blue': '#4D9EFA',
        'topical-blue': '#C8E1FD',
        'cloudy-grey': '#6D6A71',
        nobel: '#B1AFB3',
        pearl: '#F3EFFB',
        'santa-grey': '#9C9FB7',
        mercury: '#E0E5EB',
        fantasy: '#F5F5F8',
        'sliver-sand': '#C1C1C1',
        'pink-pearl': '#F29EEB',
        'rose-white': '#FEF5FD',
        'purple-70': '#9163CA',
        'purple-40': '#E6DDF4',
        'bright-grey': '#344054',
        'davy-grey': '#475467',
      },
    },
  },
  plugins: [],
}
export default config
